services:
  freeradius:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: freeradius-lab
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "18121:18121/udp"
    volumes:
      - radius-logs:/var/log/radius

volumes:
  radius-logs:
