all:
  hosts:
    freeradius:
      ansible_host: i-01a902880b5268067
      ansible_connection: amazon.aws.aws_ssm
      ansible_aws_ssm_bucket_name: freeradius-lab-rpms-855323747881
      ansible_aws_ssm_region: us-east-2
