---
- name: Restart radiusd
  ansible.builtin.systemd:
    name: radiusd
    state: restarted
    daemon_reload: true
  when: not (freeradius_docker_mode | default(false))

- name: Reload radiusd
  ansible.builtin.systemd:
    name: radiusd
    state: reloaded
  when: not (freeradius_docker_mode | default(false))
