---
- name: Install FreeRADIUS
  ansible.builtin.include_tasks: install.yml
  when: not (freeradius_docker_mode | default(false))

- name: Configure FreeRADIUS
  ansible.builtin.include_tasks: configure.yml

- name: Start FreeRADIUS service
  ansible.builtin.include_tasks: service.yml
  when: not (freeradius_docker_mode | default(false))
