---
- name: Install Vector
  ansible.builtin.include_tasks: install.yml

- name: Configure Vector
  ansible.builtin.include_tasks: configure.yml

- name: Start Vector service
  ansible.builtin.include_tasks: service.yml
